print('-'*40)
p1 = str(input('digite seu nome: '))
p2 = str(input('digite seu nome: '))
p3 = str(input('digite seu nome: '))
t1 = int(input('Digite seu telefone: '))
t2 = int(input('Digite seu telefone: '))
t3 = int(input('Digite seu telefone: '))
print('nome:{} telefone:{}\n nome:{} telefone:{}\n nome:{} telefone:{}'.format(p1,t1,p2,t2,p3,t3) )

print('-'*40)
