f1 = str(input('Digite o nome do funcinário 1 : '))
f2 = str(input('Digite o nome do funcinário 2 : '))
f3 = str(input('Digite o nome do funcinário 3 : '))
f4 = str(input('Digite o nome do funcinário 4 : '))
f5 = str(input('Digite o nome do funcinário 5 : '))
f6 = str(input('Digite o nome do funcinário 6 : '))
f7 = str(input('Digite o nome do funcinário 7 : '))
f8 = str(input('Digite o nome do funcinário 8 : '))
f9 = str(input('Digite o nome do funcinário 9 : '))
f10 = str(input('Digite o nome do funcinário 10 : '))

sex1 = str(input('Digite sexo do funcionário 1: '))
sex2 = str(input('Digite sexo do funcionário 2: '))
sex3 = str(input('Digite sexo do funcionário 3: '))
sex4 = str(input('Digite sexo do funcionário 4: '))
sex5 = str(input('Digite sexo do funcionário 5: '))
sex6 = str(input('Digite sexo do funcionário 6: '))
sex7 = str(input('Digite sexo do funcionário 7: '))
sex8 = str(input('Digite sexo do funcionário 8: '))
sex9 = str(input('Digite sexo do funcionário 9: '))
sex10 = str(input('Digite sexo do funcionário 10: '))

sal1 = float(input('Digite o salario do funcionário 1: '))
sal2 = float(input('Digite o salario do funcionário 2: '))
sal3 = float(input('Digite o salario do funcionário 3: '))
sal4 = float(input('Digite o salario do funcionário 4: '))
sal5 = float(input('Digite o salario do funcionário 5: '))
sal6 = float(input('Digite o salario do funcionário 6: '))
sal7 = float(input('Digite o salario do funcionário 7: '))
sal8 = float(input('Digite o salario do funcionário 8: '))
sal9 = float(input('Digite o salario do funcionário 9: '))
sal10 = float(input('Digite o salario do funcionário 10: '))

print('O nome do funcionário 1 é {}, seu sexo é {} e seu salário é {}'.format(f1,sex1,sal1))
print('O nome do funcionário 2 é {}, seu sexo é {} e seu salário é {}'.format(f2,sex2,sal2))
print('O nome do funcionário 3 é {}, seu sexo é {} e seu salário é {}'.format(f3,sex3,sal3))
print('O nome do funcionário 4 é {}, seu sexo é {} e seu salário é {}'.format(f4,sex4,sal4))
print('O nome do funcionário 5 é {}, seu sexo é {} e seu salário é {}'.format(f5,sex5,sal5))
print('O nome do funcionário 6 é {}, seu sexo é {} e seu salário é {}'.format(f6,sex6,sal6))
print('O nome do funcionário 7 é {}, seu sexo é {} e seu salário é {}'.format(f7,sex7,sal7))
print('O nome do funcionário 8 é {}, seu sexo é {} e seu salário é {}'.format(f8,sex8,sal8))
print('O nome do funcionário 9 é {}, seu sexo é {} e seu salário é {}'.format(f9,sex9,sal9))
print('O nome do funcionário 10 é {}, seu sexo é {} e seu salário é {}'.format(f10,sex10,sal10))

mediasal = (sal1+sal2+sal3+sal4+sal5+sal6+sal7+sal8+sal9+sal10/10)
print('A media dos salarios é {}'.format(mediasal))